version: '3'
services:
  db:
    container_name: db
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=buzon_vecinal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server/public/:/var/www/html
    ports:
      - 80:80
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
