version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=buzon_vecinal
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  www:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./public/:/var/www/html
    ports:
      - 80:80
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
